language: node_js
node_js:
- 12
- 13
- 14
- 15
- 16
deploy:
  provider: npm
  skip_cleanup: true
  email: honza.machala@seznam.cz
  api_key:
    secure: jcBU3QM4gTMmJ9JQlq1Sax1tBoARg4OdsEltEqiBN8YarNMr0/VA1kBE9MysMRZ3CNFB18AbuzyDcUj6RrLxa8B58ZOP9sBob+66Rp4BAIuY3IJu8eRNfUis6Uoh/ODuVe/GAJ5ZenKJv4lpHbYQvX7xFe5ha+SrKIs+kDMvHs35HZKB4t2okwuiUpc/pr2J0cFQRTSBJm1Aw9XPieJsPNi2URfgv/yRApv2jPhNijEkncO+1NG5MYHMPEXgHPuIOiuN1xcY/JY0ls7Okgj8gR3i/Wy3CkiTe3HMhLviTZM6dC4Hzp5aWgV8bO3qBXSJqoC9Q+ucqdO1LlTGcHQYQkmrRaYrtHYxnuqqyFOe/DwkgmgLPFyoAYAUmluOodNuYIlw29pvOSjOemw+8ofSH2gZKC3VklqSeIvNXA0hj2vh/ObMQC1s9Yqcn1xFkR1owPvke+VQ+w1S/0bit6+ohZPK3T+6UOkqDe8f+sYDbonbsUsgEiHgOn9nf+fs4u9jc8+TCHZCf61YAYJTqb0PSyWcexeSeaQUfQruE+etft+lymvDlq2zztcT0n2SDlzSAPTosqarEwIwCR7mqoJ2tcKuMja6NKCfBYTn4kp98lu9NQNcRx9VwURr2iaCf7RcocKbCvC4hn/OI3b25HAJQDo3HdLEV31JNAIdudZC3AQ=
  on:
    tags: true
    repo: HonzaMac/winston-influx
